# Generated by Django 4.0.6 on 2022-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_image_photo_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='photo',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
    ]
