# Generated by Django 4.0.6 on 2022-07-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_description_photo_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
