# Generated by Django 4.0.6 on 2022-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_rename_name_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='focus_length',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
