# Generated by Django 4.0.6 on 2022-07-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_aperture_photo_camera_name_photo_focus_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='focus_length',
            new_name='focal_length',
        ),
    ]
