# Generated by Django 4.1.7 on 2023-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_rename_focus_length_photo_focal_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(blank=True, to='photos.category'),
        ),
    ]
